spring:
  datasource:
    url: jdbc:h2:mem:musinsa
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

server:
  port: 8080
  
logging:
  level:
    com.musinsa.codi.domain.service.command: DEBUG
    com.musinsa.codi.common.aop: DEBUG
    com.musinsa.codi.adapter.outbound.event: DEBUG 